baseURL = "https://example.com"
languageCode = "en-us"
theme = "hugo-tanka-master"
title = "Technical Writing Repo"
<<<<<<< HEAD
author = "Nan Xiao"
canonifyurls = true

enableEmoji = true
hasCJKLanguage = false

pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

=======
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.parser]
attribute = true
autoHeadingID = true
[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false
[markup.highlight]
codeFences = true
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4
[markup.tableOfContents]
endLevel = 6
startLevel = 2
[[menu.nav]]
name = "contacts"
url = "/contacts/"
weight = 5
[[menu.nav]]
name = "google tw"
url = "/googletw/"
weight = 4
[[menu.nav]]
name = "resources"
url = "/resources"
weight = 3
[[menu.nav]]
name = "glossary"
url = "/glossary/"
weight = 2
[[menu.nav]]
name = "news"
url = "/news/"
weight = 1
>>>>>>> e8e7d8a7f339d51bc247a07bcaba13253ee24435
[params]
  sitename = "Hugo Tanka Theme"
  faviconfile = "images/favicon.png"
  highlightjs = true
  highlightjslanguages = ["r", "python", "stan"]
  uselatex = true
  progressively = false
# commentsrepo = "user/repo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.primary]]
    name = "GitHub"
    url = "https://github.com/nanxstats"
    weight = 3
[[menu.primary]]
    name = "Twitter"
    url = "https://twitter.com/nanxstats"
    weight = 4
[[menu.primary]]
    name = "Subscribe"
    url = "/index.xml"
    weight = 5

