baseURL = "https://example.com"
languageCode = "en-us"
theme = "minimal-master"
title = "Technical Writing Repo"
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.parser]
attribute = true
autoHeadingID = true
[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false
[markup.highlight]
codeFences = true
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4
[markup.tableOfContents]
endLevel = 6
startLevel = 2
[[menu.nav]]
name = "forestry"
url = "yandex.ru"
weight = 6
[[menu.nav]]
name = "contacts"
url = "/contacts/"
weight = 5
[[menu.nav]]
name = "google tw"
url = "/googletw/"
weight = 4
[[menu.nav]]
name = "resources"
url = "/resources"
weight = 3
[[menu.nav]]
name = "glossary"
url = "/glossary/"
weight = 2
[[menu.nav]]
name = "news"
url = "/news/"
weight = 1
[params]
contentBackgroundColor = "#fff"
contentLinkColor = "#007bff"
contentLinkHoverColor = "#0056b3"
contentTextColor = "#212529"
cookieConsent = true
customBlockquoteStyle = true
customCodeStyle = true
customDateFormat = "Jan 2, 2006"
description = "Some description"
faviconMsApplicationTileColor = "#da532c"
faviconSafariPinnedTabColor = "#5bbad5"
faviconThemeColor = "#ffffff"
googleAnalytics = "UA-123456789-1"
includeBootstrapJs = true
navbarBackgroundColor = "#212529"
navbarLinkColor = "rgba(255, 255, 255, 0.75)"
navbarLinkHoverColor = "rgba(255, 255, 255, 1)"
showPostSummary = false
wrapperMaxWidth = "800px"
[permalinks]
post = "/:filename/"
[taxonomies]
category = "categories"
tag = "tags"
