baseURL = "https://docops.neltify.com"
languageCode = "en-us"
theme = "hugo-tanka-master"
title = "Technical Writing Repo"

canonifyurls = true

enableEmoji = true
hasCJKLanguage = true

pygmentsstyle = "vs"
pygmentscodefences = true

[params]
  sitename = "Technical Writing Repo"
  faviconfile = "images/favicon.png"
  highlightjs = true
  highlightjslanguages = ["r", "python", "stan"]
  uselatex = true
  progressively = true
# commentsrepo = "user/repo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.primary]]
    name = "news"
    url = "/news"
    weight = 1
[[menu.primary]]
    name = "glossary"
    url = "/glossary/"
    weight = 2
[[menu.primary]]
    name = "googletw"
    url = "/googletw"
    weight = 3
[[menu.primary]]
    name = "resources"
    url = "/resources"
    weight = 4

