baseURL = "https://example.com"
languageCode = "en-us"
theme = "hugo-tanka-master"
title = "Technical Writing Repo"

canonifyurls = true

enableEmoji = true
hasCJKLanguage = true

pygmentsstyle = "vs"
pygmentscodefences = true

[params]
  sitename = "Technical Writing Repo"
  faviconfile = "images/favicon.png"
  highlightjs = true
  highlightjslanguages = ["r", "python", "stan"]
  uselatex = true
  progressively = true
# commentsrepo = "user/repo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.primary]]
    name = "GitHub"
    url = "https://github.com/nanxstats"
    weight = 3
[[menu.primary]]
    name = "Twitter"
    url = "https://twitter.com/nanxstats"
    weight = 4
[[menu.primary]]
    name = "Subscribe"
    url = "/index.xml"
    weight = 5
